language: python
python:
  - "3.4"
  - "3.5"

install: "pip install -r requirements.txt"
# script: nosetests
script:
  - pip install git+git://github.com/tcmoore3/timplotlib.git@master
  - coverage run --rcfile=.coveragerc --source=msibi_utils setup.py test
after_success:
  - coveralls
